---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bus
  template:
    metadata:
      name: mytemp
      labels:
        app: bus
    spec:
      containers:
        - name: cont-12
          image: shaikmustafa/mygame
          ports:
            - containerPort: 80
