---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie
  template:
    metadata:
      name: mytemp
      labels:
        app: movie
    spec:
      containers:
        - name: cont-11
          image: shaikmustafa/paytm:movie
          ports:
            - containerPort: 80
